[tool.poetry]
name = "octopy"
version = "0.1.0"
description = ""
authors = ["Brett Kuhlman <kuhlman-labs@github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
gql = "^3.3.0"
aiohttp = "^3.8.1"
python-dotenv = "^0.20.0"
requests = "^2.28.1"
pytest = "^7.1.2"
black = "^22.6.0"
pre-commit = "^2.19.0"
autoflake = "^1.4"
isort = "^5.10.1"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
gql = "^3.3.0"
aiohttp = "^3.8.1"
python-dotenv = "^0.20.0"
requests = "^2.28.1"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
